apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-compliance-operator
    namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      cattle.io/app: compliance-operator
  template:
    metadata:
      labels:
        cattle.io/app: compliance-operator
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: compliance-operator
          image: "{{ template "system_default_registry" . }}{{ .Values.complianceOperator.image.name }}:{{ .Values.complianceOperator.image.tag }}"
          imagePullPolicy: {{ .Values.complianceOperator.imagePullPolicy }}
          env:
          - name: STIGATRON_NAMESPACE
            value: {{ .Release.Namespace | quote }}
      serviceAccountName: {{ .Values.complianceOperator.serviceAccountName }}-compliance-operator-sa