apiVersion: v1
kind: Secret
metadata:
  name: heimdall-operator
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.heimdallOperator.database.host | default (printf "%s-heimdall2-postgresql" .Release.Name) | b64enc | quote }}
  DB_PORT: {{ .Values.heimdallOperator.database.port | b64enc | quote }}
  DB_NAME: {{ .Values.heimdallOperator.database.name | b64enc | quote }}
  DB_USER: {{ .Values.heimdallOperator.database.user | b64enc | quote }} 
  DB_PASS: {{ .Values.heimdallOperator.database.password | b64enc | quote }}
  {{- if .Values.heimdallOperator.database.sslMode }}
  SSL_MODE: {{ .Values.heimdallOperator.database.sslMode | b64enc | quote }}
  {{- end }}


