apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stigatron-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-5"
subjects:
  - kind: ServiceAccount
    name: stigatron-hook
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: stigatron-hook
  apiGroup: rbac.authorization.k8s.io