apiVersion: v1
kind: ServiceAccount
metadata:
  name: stigatron-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"